const state = {};
let currentStep = 1;
const stepNames = ["Your floor","Finish and preparation","Job details","Photos and contact details"];
const intro=document.getElementById('introScreen'),wizard=document.getElementById('wizard'),result=document.getElementById('resultScreen'),form=document.getElementById('estimateForm');
function showStep(step){currentStep=step;document.querySelectorAll('.step').forEach(s=>s.classList.toggle('active',Number(s.dataset.step)===step));document.getElementById('stepLabel').textContent=`Step ${step} of 4`;document.getElementById('stepName').textContent=stepNames[step-1];document.getElementById('progressFill').style.width=`${step*25}%`;document.getElementById('backBtn').textContent=step===1?'Floor options':'Back';document.getElementById('nextBtn').textContent=step===4?'Submit details':'Continue';document.getElementById('nextBtn').disabled=step===1&&!state.service;if(step===2)updateFinishOptions();updateFlowProgress(step);window.scrollTo({top:0,behavior:'smooth'});}
document.getElementById('startBtn').addEventListener('click',()=>{intro.classList.add('hidden');wizard.classList.remove('hidden');showStep(1);});
document.querySelectorAll('.single-choice').forEach(group=>group.addEventListener('click',e=>{const btn=e.target.closest('[data-value]');if(!btn)return;group.querySelectorAll('[data-value]').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');state[group.dataset.name]=btn.dataset.value;if(group.dataset.name==='service'){document.getElementById('floorDetails').classList.remove('hidden');document.getElementById('nextBtn').disabled=false;}if(group.dataset.name==='measure_mode')updateMeasureMode(btn.dataset.value);if(group.dataset.name==='cleared')document.getElementById('clearedNote').classList.toggle('hidden',btn.dataset.value==='Yes');if(group.dataset.name==='service'){['exposure','sheen','sealer','finish_example'].forEach(key=>{delete state[key];document.querySelectorAll(`[data-name="${key}"] [data-value]`).forEach(b=>{b.classList.remove('selected');b.setAttribute('aria-pressed','false');});});updateFinishOptions();}if(group.dataset.name==='finish_example'){const presets={'Full Polish High Gloss':['Medium / large aggregate','High polish / gloss'],'Full Exposure Semi-Gloss':['Medium / large aggregate','Semi-gloss / lower sheen'],'Small Exposure Low Sheen':['Salt & pepper','Low sheen']};[state.exposure,state.sheen]=presets[btn.dataset.value];for(const name of ['exposure','sheen'])document.querySelectorAll(`[data-name="${name}"] [data-value]`).forEach(b=>{const selected=b.dataset.value===state[name];b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected));});}}));
function updateMeasureMode(value){form.elements.known_area.disabled=value!=='Known area';document.querySelectorAll('.room-row input').forEach(input=>input.disabled=value!=='Room calculator');document.getElementById('knownAreaWrap').classList.toggle('hidden',value!=='Known area');document.getElementById('roomCalcWrap').classList.toggle('hidden',value!=='Room calculator');if(value==='Room calculator'&&document.querySelectorAll('.room-row').length===0)addRoom();}
function updateFinishOptions(){const service=state.service||'';document.getElementById('creamSurfaceNote').classList.toggle('hidden',service!=='Cream / industrial finish');document.getElementById('prepContactNote').classList.toggle('hidden',service!=='Floor preparation / levelling');document.getElementById('creamOptions').classList.toggle('hidden',service!=='Cream / industrial finish');updatePreparationQuestions();document.querySelector('.step[data-step="2"] h2').textContent=service==='Floor preparation / levelling'?'Your preparation':'What look are you after?';document.getElementById('lowSheenOptions').classList.toggle('hidden',service!=='Grind and polish — low sheen');document.getElementById('bushOptions').classList.toggle('hidden',service!=='Bush Hammer');document.getElementById('polishOptions').classList.toggle('hidden',service!=='Full polished concrete');document.getElementById('sealOptions').classList.toggle('hidden',service!=='Grind & seal');document.getElementById('prepOptions').classList.toggle('hidden',service!=='Floor preparation / levelling'&&service!=='Other / Not sure');}
function enforceExclusiveCheckboxes(name,exclusiveValues){const boxes=[...form.querySelectorAll(`input[name="${name}"]`)];boxes.forEach(box=>box.addEventListener('change',()=>{if(!box.checked)return;if(exclusiveValues.includes(box.value))boxes.forEach(other=>{if(other!==box)other.checked=false;});else boxes.forEach(other=>{if(exclusiveValues.includes(other.value))other.checked=false;});}));}
enforceExclusiveCheckboxes('access',['Straightforward access','Not sure']);enforceExclusiveCheckboxes('condition',['Nothing obvious','Not sure']);
let photoInput=null,photoList=null,selectedPhotos=[];
function setupPhotoPicker(){const placeholder=document.querySelector('.upload-placeholder');if(!placeholder)return;placeholder.innerHTML=`<strong>Add photos</strong><span>Overall area, close-up of the slab, edges, cracks, coatings and damaged areas</span><label class="photo-picker" for="photos">Choose photos</label><input aria-label="Choose up to five optional project photos" id="photos" name="photos" type="file" accept="image/*" multiple><span class="muted">Optional — up to 5 photos. Large phone photos are resized automatically.</span><div id="photoList" class="muted"></div>`;photoInput=document.getElementById('photos');photoList=document.getElementById('photoList');photoInput.addEventListener('change',()=>{const files=[...photoInput.files];if(files.length>5){alert('Please select up to 5 photos.');photoInput.value='';selectedPhotos=[];photoList.textContent='';return;}selectedPhotos=files;photoList.innerHTML=files.length?files.map(f=>`<div>${escapeHtml(f.name)}</div>`).join(''):'';});}
setupPhotoPicker();
function compressPhoto(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const max=1600,scale=Math.min(1,max/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);let quality=.82;let data=canvas.toDataURL('image/jpeg',quality);while(data.length>3.4*1024*1024&&quality>.45){quality-=.08;data=canvas.toDataURL('image/jpeg',quality);}resolve({filename:file.name.replace(/\.[^.]+$/, '')+'.jpg',content:data});};img.src=reader.result;};reader.readAsDataURL(file);});}
async function uploadPhotos(){if(!selectedPhotos.length)return[];const folder=`${value('name')} - ${value('address')}`;const uploaded=[];for(const file of selectedPhotos){const photo=await compressPhoto(file);const response=await fetch('/api/upload',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filename:photo.filename,content:photo.content,folder})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Photo upload failed');uploaded.push(data);}return uploaded;}
function addRoom(){const wrap=document.getElementById('roomRows');const row=document.createElement('div');row.className='room-row';row.innerHTML=`<select class="room-name"><option>Living area</option><option>Garage</option><option>Workshop</option><option>Warehouse</option><option>Retail / commercial</option><option>Patio / outdoor</option><option>Other</option></select><input class="room-length" type="number" min="0" step="0.1" placeholder="Length m"><input class="room-width" type="number" min="0" step="0.1" placeholder="Width m"><button class="remove-room" type="button" title="Remove">×</button>`;wrap.appendChild(row);row.querySelectorAll('input,select').forEach(el=>el.addEventListener('input',calcRooms));row.querySelector('.remove-room').addEventListener('click',()=>{row.remove();calcRooms();});}
function calcRooms(){let total=0;document.querySelectorAll('.room-row').forEach(r=>{total+=(Number(r.querySelector('.room-length').value)||0)*(Number(r.querySelector('.room-width').value)||0)});document.getElementById('roomTotal').textContent=total.toFixed(1);}
document.getElementById('addRoomBtn').addEventListener('click',addRoom);document.getElementById('backBtn').addEventListener('click',()=>{if(currentStep>1)showStep(currentStep-1);else{wizard.classList.add('hidden');intro.classList.remove('hidden');document.getElementById('startBtn').focus();window.scrollTo({top:0,behavior:'smooth'});}});
function checked(name){return[...form.querySelectorAll(`input[name="${name}"]:checked`)].map(x=>x.value).join(', ')||'None selected'}function value(name){return form.elements[name]?.value||'Not entered'}
function roomSummary(){if(state.measure_mode==='Known area')return`${form.elements.known_area.value||'Not entered'} m²`;if(state.measure_mode==='Not sure')return'Not sure';if(state.measure_mode==='Room calculator'){const parts=[];document.querySelectorAll('.room-row').forEach(r=>{const n=r.querySelector('.room-name').value,l=Number(r.querySelector('.room-length').value)||0,w=Number(r.querySelector('.room-width').value)||0;if(l&&w)parts.push(`${n} ${(l*w).toFixed(1)} m²`);});return parts.length?`${parts.join(', ')} — total ${document.getElementById('roomTotal').textContent} m²`:'No measurements entered';}return'Not selected';}
function summaryRows(){const finish=state.service==='Cream / industrial finish'?`Cream / industrial finish; ${state.sheen||'Sheen not selected'}`:state.service==='Grind and polish — low sheen'?`Small exposure; ${state.sheen||'Sheen not selected'}`:state.service==='Full polished concrete'?`Medium / large exposure; ${state.sheen||'Sheen not selected'}`:state.service==='Grind & seal'?(state.sealer||'Sealer not selected'):state.service==='Bush Hammer'?'Textured Decorative Finish (Bush Hammer)':value('prep_note');const photoText=state.uploadedPhotos?.length?`${state.uploadedPhotos.length} uploaded to Dropbox`:'None';return[['Service',state.service||'Not selected'],['Area',roomSummary()],['Concrete',value('concrete_age')],['Current surface',value('covering')],['Finish / preference',finish],...(state.service==='Floor preparation / levelling'?[['Preparation for',form.elements.prep_target.selectedOptions[0].text],['Substrate',form.elements.prep_substrate.selectedOptions[0].text],...(form.elements.prep_target.value==='coating'&&form.elements.prep_substrate.value==='timber'?[['Tongue-and-groove timber',form.elements.prep_tongue_groove.selectedOptions[0].text]]:[])]:[]),['Slab condition',checked('condition')],['Area cleared',state.cleared||'Not selected'],['Access',checked('access')],['Timeframe',value('timeframe')],['Photos',photoText],['Customer',value('name')],['Phone',value('phone')],['Email',value('email')],['Job address',value('address')],['Comments',value('comments')]];}
async function sendEnquiry(){state.submissionId ||= crypto.randomUUID();state.submittedAt ||= new Date().toISOString();const response=await fetch('/api/enquiry',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'Concrete',submissionId:state.submissionId,submittedAt:state.submittedAt,customer:{name:value('name'),phone:value('phone'),email:value('email'),address:value('address')},rows:summaryRows(),photos:state.uploadedPhotos||[],concrete:concreteInput()})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Enquiry email failed');return data;}
document.getElementById('nextBtn').addEventListener('click',async()=>{if(currentStep<4){if(currentStep===1&&!validateConcreteMeasurements())return;showStep(currentStep+1);return;}if(!validateConcreteMeasurements())return;if(!form.reportValidity())return;const btn=document.getElementById('nextBtn');btn.disabled=true;setSubmissionControls(true);btn.textContent=selectedPhotos.length?'Preparing photos & submitting…':'Submitting…';try{const uploaded=await uploadPhotos();state.uploadedPhotos=uploaded;const submission=await sendEnquiry();state.estimate=submission.estimate;state.customerEmailSent=submission.customerEmailSent;buildSummary();renderConcreteEstimate();wizard.classList.add('hidden');result.classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'});}catch(err){alert(`We couldn't submit the enquiry: ${err.message}. Please try again.`);}finally{setSubmissionControls(false);btn.disabled=false;btn.textContent='Submit details';}});
function resetEnquiry(){wizard.classList.add('hidden');currentStep=1;document.querySelectorAll('[aria-pressed]').forEach(b=>b.setAttribute('aria-pressed','false'));result.classList.add('hidden');intro.classList.remove('hidden');form.reset();document.querySelectorAll('.selected').forEach(e=>e.classList.remove('selected'));document.querySelectorAll('#roomRows .room-row').forEach(e=>e.remove());if(photoList)photoList.textContent='';selectedPhotos=[];Object.keys(state).forEach(k=>delete state[k]);document.getElementById('floorDetails').classList.add('hidden');updateMeasureMode(null);document.getElementById('roomTotal').textContent='0.0';document.getElementById('clearedNote').classList.add('hidden');document.getElementById('surfaceReviewNote').classList.add('hidden');updateFinishOptions();}
function buildSummary(){const rows=summaryRows();document.getElementById('summary').innerHTML=rows.map(([k,v])=>`<div class="summary-row"><b>${escapeHtml(k)}</b><span>${escapeHtml(v)}</span></div>`).join('');}
function escapeHtml(str){return String(str).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}

function concreteInput(){
  let area = null;
  if(state.measure_mode === 'Known area') area = Number(form.elements.known_area.value);
  if(state.measure_mode === 'Room calculator') area = [...document.querySelectorAll('.room-row')].reduce((total,row)=>total+Number(row.querySelector('.room-length').value)*Number(row.querySelector('.room-width').value),0);
  return {area,preparationTarget:form.elements.prep_target.value,substrate:form.elements.prep_substrate.value,tongueGroove:form.elements.prep_tongue_groove.value,service:state.service,sealer:state.sealer,surface:form.elements.covering.value,conditions:[...form.querySelectorAll('input[name="condition"]:checked')].map(box=>box.value)};
}
function validateConcreteMeasurements(){
  if(state.measure_mode === 'Room calculator'){
    const rooms = [...document.querySelectorAll('.room-row')];
    if(!rooms.length || rooms.some(row=>!['.room-length','.room-width'].every(selector=>Number(row.querySelector(selector).value)>0))){
      showStep(1);alert('Please enter a positive length and width for each room, or choose Not sure.');return false;
    }
  }
  const area = concreteInput().area;
  if(area !== null && (!Number.isFinite(area) || area <= 0 || area > 100000)){
    showStep(1);alert('Please enter a valid positive floor area, or choose Not sure.');return false;
  }
  return true;
}
function renderConcreteEstimate(){
  const estimate = state.estimate;
  const money = value=>new Intl.NumberFormat('en-NZ',{style:'currency',currency:'NZD'}).format(value);
  const hasPrice = estimate?.total != null || (estimate?.low != null && estimate?.high != null);
  document.getElementById('estimateTotal').textContent = estimate?.total != null ? money(estimate.total) : hasPrice ? money(estimate.low)+' – '+money(estimate.high) : 'Discuss pricing with Jamie';
  document.getElementById('estimateGst').textContent = hasPrice ? estimate.gst+' · NZD' : 'Jamie will confirm scope and pricing with you.';
  document.getElementById('estimateIncluded').textContent = estimate?.included || '';
  document.getElementById('estimateReview').innerHTML = (estimate?.review || []).map(item=>'<li>'+escapeHtml(item)+'</li>').join('');
  document.getElementById('estimateDisclaimer').textContent = estimate?.disclaimer || 'Jamie will review your enquiry and confirm pricing.';
  document.getElementById('customerEmailStatus').textContent = state.customerEmailSent ? 'A copy has been sent to your email address. You can reply to Jamie with any questions.' : 'Your enquiry has been received. If your pricing email does not arrive, please contact Jamie.';
}


let submitting=false;function setSubmissionControls(busy){submitting=busy;['cancelBtn','changeTypeBtn','backBtn'].forEach(id=>document.getElementById(id).disabled=busy);}document.getElementById('restartBtn').addEventListener('click',resetEnquiry);document.getElementById('cancelBtn').addEventListener('click',()=>{if(!submitting)resetEnquiry();});document.getElementById('changeTypeBtn').addEventListener('click',()=>{if(!submitting)window.location.href="index.html";});form.addEventListener('submit',e=>{e.preventDefault();document.getElementById('nextBtn').click();});

form.elements.covering.addEventListener('change',e=>{document.getElementById('surfaceReviewNote').classList.toggle('hidden',!e.target.value||e.target.value==='Bare concrete');});

function updatePreparationQuestions(){const prep=state.service==='Floor preparation / levelling';document.querySelector('[data-stage="2"]').lastChild.textContent=prep?'Preparation':'Finish';document.getElementById('prepTongueGroove').classList.toggle('hidden',!prep||form.elements.prep_target.value!=='coating'||form.elements.prep_substrate.value!=='timber');const recommendation=document.getElementById('prepRecommendation');const method=form.elements.prep_target.value==='vinyl'?(form.elements.prep_substrate.value==='timber'?'Recommended preparation: hardboard overlay. Jamie will confirm suitability after inspection.':form.elements.prep_substrate.value==='concrete'?'Recommended preparation: grind and skim. Jamie will confirm suitability after inspection.':''):'';recommendation.textContent=method;recommendation.classList.toggle('hidden',!prep||!method);const visible=!prep||form.elements.prep_target.value==='coating';document.getElementById('conditionOptions').classList.toggle('hidden',!visible);if(!visible)form.querySelectorAll('input[name="condition"]').forEach(box=>box.checked=false);if(currentStep===2)document.getElementById('stepName').textContent=prep?'Your preparation':stepNames[1];}
form.elements.prep_target.addEventListener('change',updatePreparationQuestions);
form.elements.prep_substrate.addEventListener('change',updatePreparationQuestions);
