const state = {};
let currentStep = 1;
const stepNames = ["Your floor","Finish and preparation","Job details","Photos and contact details"];
const intro=document.getElementById('introScreen'),wizard=document.getElementById('wizard'),result=document.getElementById('resultScreen'),form=document.getElementById('estimateForm');
function showStep(step){currentStep=step;document.querySelectorAll('.step').forEach(s=>s.classList.toggle('active',Number(s.dataset.step)===step));document.getElementById('stepLabel').textContent=`Step ${step} of 4`;document.getElementById('stepName').textContent=stepNames[step-1];document.getElementById('progressFill').style.width=`${step*25}%`;document.getElementById('backBtn').textContent=step===1?'Floor options':'Back';document.getElementById('nextBtn').textContent=step===4?'Submit details':'Continue';document.getElementById('nextBtn').disabled=step===1&&!state.service;updateFlowProgress(step);window.scrollTo({top:0,behavior:'smooth'});}
document.getElementById('startBtn').addEventListener('click',()=>{intro.classList.add('hidden');wizard.classList.remove('hidden');showStep(1);});
document.querySelectorAll('.single-choice').forEach(group=>group.addEventListener('click',e=>{const btn=e.target.closest('[data-value]');if(!btn)return;group.querySelectorAll('[data-value]').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');state[group.dataset.name]=btn.dataset.value;if(group.dataset.name==='service'){document.getElementById('floorDetails').classList.remove('hidden');document.getElementById('nextBtn').disabled=false;}if(group.dataset.name==='service'){document.getElementById('serviceOtherWrap').classList.toggle('hidden',btn.dataset.value!=='Other / Not sure');document.getElementById('timberFinishOptions').classList.toggle('hidden',btn.dataset.value==='Sanding only');}if(group.dataset.name==='appearance'){if(btn.dataset.value==='Natural Oil Finish')form.elements.finish.value='oil';else if(form.elements.finish.value==='oil')form.elements.finish.value='unknown';updateOilCoatingChoice();}if(group.dataset.name==='measure_mode')updateMeasureMode(btn.dataset.value);if(group.dataset.name==='cleared')document.getElementById('clearedNote').classList.toggle('hidden',btn.dataset.value==='Yes');}));
function updateMeasureMode(value){form.elements.known_area.disabled=value!=='Known area';document.querySelectorAll('.room-row input').forEach(input=>input.disabled=value!=='Room calculator');document.getElementById('knownAreaWrap').classList.toggle('hidden',value!=='Known area');document.getElementById('roomCalcWrap').classList.toggle('hidden',value!=='Room calculator');if(value==='Room calculator'&&document.querySelectorAll('.room-row').length===0)addRoom();}
document.querySelector('[name="timber_type"]').addEventListener('change',e=>document.getElementById('timberOther').classList.toggle('hidden',e.target.value!=='Other'));
document.getElementById('projectType').addEventListener('change',e=>document.getElementById('projectStage').classList.toggle('hidden',!e.target.value.startsWith('Yes')));
function enforceExclusiveCheckboxes(name,exclusiveValues){const boxes=[...form.querySelectorAll(`input[name="${name}"]`)];boxes.forEach(box=>box.addEventListener('change',()=>{if(!box.checked)return;if(exclusiveValues.includes(box.value))boxes.forEach(other=>{if(other!==box)other.checked=false;});else boxes.forEach(other=>{if(exclusiveValues.includes(other.value))other.checked=false;});}));}
enforceExclusiveCheckboxes('access',['Straightforward access','Not sure']);enforceExclusiveCheckboxes('condition',['Nothing obvious','Not sure']);
let photoInput=null,photoList=null,selectedPhotos=[];
function setupPhotoPicker(){const placeholder=document.querySelector('.upload-placeholder');if(!placeholder)return;placeholder.innerHTML=`<strong>Add photos</strong><span>Overall floor, close-up of timber, and any damaged areas</span><label class="photo-picker" for="photos">Choose photos</label><input aria-label="Choose up to five optional project photos" id="photos" name="photos" type="file" accept="image/*" multiple><span class="muted">Optional — up to 5 photos. Large phone photos are resized automatically.</span><div id="photoList" class="muted"></div>`;photoInput=document.getElementById('photos');photoList=document.getElementById('photoList');photoInput.addEventListener('change',()=>{const files=[...photoInput.files];if(files.length>5){alert('Please select up to 5 photos.');photoInput.value='';selectedPhotos=[];photoList.textContent='';return;}selectedPhotos=files;photoList.innerHTML=files.length?files.map(f=>`<div>${escapeHtml(f.name)}</div>`).join(''):'';});}
setupPhotoPicker();
function compressPhoto(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const max=1600,scale=Math.min(1,max/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);let quality=.82;let data=canvas.toDataURL('image/jpeg',quality);while(data.length>3.4*1024*1024&&quality>.45){quality-=.08;data=canvas.toDataURL('image/jpeg',quality);}resolve({filename:file.name.replace(/\.[^.]+$/, '')+'.jpg',content:data});};img.src=reader.result;};reader.readAsDataURL(file);});}
async function uploadPhotos(){if(!selectedPhotos.length)return[];const folder=`${value('name')} - ${value('address')}`;const uploaded=[];for(const file of selectedPhotos){const photo=await compressPhoto(file);const response=await fetch('/api/upload',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filename:photo.filename,content:photo.content,folder})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Photo upload failed');uploaded.push(data);}return uploaded;}
function addRoom(){const wrap=document.getElementById('roomRows');const row=document.createElement('div');row.className='room-row';row.innerHTML=`<select class="room-name"><option>Kitchen</option><option>Dining</option><option>Lounge / Living</option><option>Hallway</option><option>Bedroom</option><option>Entrance / Foyer</option><option>Other</option></select><input class="room-length" type="number" min="0" step="0.1" placeholder="Length m"><input class="room-width" type="number" min="0" step="0.1" placeholder="Width m"><button class="remove-room" type="button" title="Remove">×</button>`;wrap.appendChild(row);row.querySelectorAll('input,select').forEach(el=>el.addEventListener('input',calcRooms));row.querySelector('.remove-room').addEventListener('click',()=>{row.remove();calcRooms();});}
function calcRooms(){let total=0;document.querySelectorAll('.room-row').forEach(r=>{total+=(Number(r.querySelector('.room-length').value)||0)*(Number(r.querySelector('.room-width').value)||0)});document.getElementById('roomTotal').textContent=total.toFixed(1);}
document.getElementById('addRoomBtn').addEventListener('click',addRoom);document.getElementById('backBtn').addEventListener('click',()=>{if(currentStep>1)showStep(currentStep-1);else{wizard.classList.add('hidden');intro.classList.remove('hidden');document.getElementById('startBtn').focus();window.scrollTo({top:0,behavior:'smooth'});}});
function checked(name){return[...form.querySelectorAll(`input[name="${name}"]:checked`)].map(x=>x.value).join(', ')||'None selected'}function value(name){return form.elements[name]?.value||'Not entered'}
function roomSummary(){if(state.measure_mode==='Known area')return`${form.elements.known_area.value||'Not entered'} m²`;if(state.measure_mode==='Not sure')return'Not sure';if(state.measure_mode==='Room calculator'){const parts=[];document.querySelectorAll('.room-row').forEach(r=>{const n=r.querySelector('.room-name').value,l=Number(r.querySelector('.room-length').value)||0,w=Number(r.querySelector('.room-width').value)||0;if(l&&w)parts.push(`${n} ${(l*w).toFixed(1)} m²`);});return parts.length?`${parts.join(', ')} — total ${document.getElementById('roomTotal').textContent} m²`:'No measurements entered';}return'Not selected';}
function summaryRows(){const timber=value('timber_type')==='Other'?value('timber_other'):value('timber_type');const photoText=state.uploadedPhotos?.length?`${state.uploadedPhotos.length} uploaded to Dropbox`:'None';return[['Service',state.service||'Not selected'],['Area',roomSummary()],['Timber',timber],['Current floor covering',value('covering')],['Desired appearance',state.appearance||'Not selected'],['Coating system',state.service==='Sanding only'?'Sanding only':form.elements.finish.selectedOptions[0].text],...preparationSummary(),['Floor condition',checked('condition')],['Areas cleared',state.cleared||'Not selected'],['Access',checked('access')],['Project type',value('project_type')],['Timeframe',value('timeframe')],['Photos',photoText],['Customer',value('name')],['Phone',value('phone')],['Email',value('email')],['Job address',value('address')],['Comments',value('comments')]];}
async function sendEnquiry(){state.submissionId ||= crypto.randomUUID();state.submittedAt ||= new Date().toISOString();const response=await fetch('/api/enquiry',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'Timber',submissionId:state.submissionId,submittedAt:state.submittedAt,customer:{name:value('name'),phone:value('phone'),email:value('email'),address:value('address')},rows:summaryRows(),photos:state.uploadedPhotos||[],timber:timberInput()})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Enquiry email failed');return data;}
document.getElementById('nextBtn').addEventListener('click',async()=>{if(currentStep<4){for(const input of document.querySelectorAll('.step.active input')){if(!input.checkValidity()){input.reportValidity();return;}}if(currentStep===1&&!validateMeasurements())return;showStep(currentStep+1);return;}if(!validateMeasurements())return;if(!form.reportValidity())return;const btn=document.getElementById('nextBtn');btn.disabled=true;btn.textContent=selectedPhotos.length?'Preparing photos & submitting…':'Submitting…';try{const uploaded=await uploadPhotos();state.uploadedPhotos=uploaded;const submission=await sendEnquiry();state.estimate=submission.estimate;state.customerEmailSent=submission.customerEmailSent;buildSummary();renderEstimate();wizard.classList.add('hidden');result.classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'});}catch(err){alert(`We couldn't submit the enquiry: ${err.message}. Please try again.`);}finally{btn.disabled=false;btn.textContent='Submit details';}});
document.getElementById('restartBtn').addEventListener('click',()=>{result.classList.add('hidden');intro.classList.remove('hidden');form.reset();document.querySelectorAll('.selected').forEach(e=>e.classList.remove('selected'));document.querySelectorAll('#roomRows .room-row').forEach(e=>e.remove());if(photoList)photoList.textContent='';selectedPhotos=[];Object.keys(state).forEach(k=>delete state[k]);document.getElementById('floorDetails').classList.add('hidden');updateMeasureMode(null);['serviceOtherWrap','timberOther','projectStage','clearedNote'].forEach(id=>document.getElementById(id).classList.add('hidden'));document.getElementById('roomTotal').textContent='0.0';updateOilCoatingChoice();});
function buildSummary(){const rows=summaryRows();document.getElementById('summary').innerHTML=rows.map(([k,v])=>`<div class="summary-row"><b>${escapeHtml(k)}</b><span>${escapeHtml(v)}</span></div>`).join('');}
function escapeHtml(str){return String(str).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}

function timberInput(){
  let area=null;
  if(state.measure_mode==='Known area') area=Number(form.elements.known_area.value);
  if(state.measure_mode==='Room calculator') area=[...document.querySelectorAll('.room-row')].reduce((sum,row)=>sum+Number(row.querySelector('.room-length').value)*Number(row.querySelector('.room-width').value),0);
  const details={area,finish:state.service==='Sanding only'?'sand':(state.service?.startsWith('Sand & coat')?form.elements.finish.value:'unknown'),largeItems:form.elements.largeItems.value===''?null:Number(form.elements.largeItems.value)};
  for(const key of ['gapFilling','carpetRemoval','fixingsRemoval','vinylRemoval','hardboard','stairs','difficultCoatings']) details[key]=form.elements[key].value;
  // A reported adhesive issue always needs review, even if the review choice says no.
  if(checked('condition').includes('Glue or adhesive'))details.difficultCoatings='yes';
  return details;
}
function validateMeasurements(){
  if(state.measure_mode==='Room calculator'){
    const rooms=[...document.querySelectorAll('.room-row')];
    if(!rooms.length||rooms.some(r=>!['.room-length','.room-width'].every(s=>Number(r.querySelector(s).value)>0))){showStep(1);alert('Please enter a positive length and width for each room, or choose Not sure.');return false;}
  }
  const area=timberInput().area;
  if(area!==null&&(!Number.isFinite(area)||area<=0||area>100000)){showStep(2);alert('Please enter a valid positive floor area, or choose Not sure.');return false;}
  return true;
}
function preparationSummary(){return [['gapFilling','Epoxy gap filling'],['carpetRemoval','Carpet removal'],['fixingsRemoval','Tacks/staples/gripper removal'],['vinylRemoval','Normal vinyl/lino removal'],['hardboard','Hardboard removal'],['stairs','Stairs to finish'],['difficultCoatings','Difficult coatings']].map(([key,label])=>[label,form.elements[key].selectedOptions[0].text]).concat([['Large items to move',form.elements.largeItems.value||'TBC'],['Preparation scope','Selected preparation covers the full measured floor area'],['Clearing notes',value('cleared_note')],['Service notes',value('service_other')]]);}
function renderEstimate(){document.getElementById('customerEmailStatus').textContent=state.customerEmailSent?'A copy has been sent to your email address. You can reply to Jamie with any questions.':'Your enquiry has been received. If your pricing email does not arrive, please contact Jamie.';const estimate=state.estimate;document.getElementById('estimateTotal').textContent=estimate?.total==null?'Jamie to confirm':new Intl.NumberFormat('en-NZ',{style:'currency',currency:'NZD'}).format(estimate.total);document.getElementById('estimateGst').textContent=estimate?.total==null?'GST will be stated with your confirmed pricing':estimate.gst+' · NZD';document.getElementById('estimateIncluded').textContent=estimate?.included||'';document.getElementById('estimateReview').innerHTML=(estimate?.review||[]).map(item=>'<li>'+escapeHtml(item)+'</li>').join('');document.getElementById('estimateDisclaimer').textContent=estimate?.disclaimer||'Jamie will review your enquiry and confirm pricing.';}


function updateOilCoatingChoice(){document.getElementById('coatingSystemChoices').classList.toggle('hidden',state.appearance==='Natural Oil Finish');}
form.elements.finish.addEventListener('change',()=>{if(form.elements.finish.value!=='oil')return;state.appearance='Natural Oil Finish';document.querySelectorAll('[data-name="appearance"] [data-value]').forEach(button=>{const selected=button.dataset.value===state.appearance;button.classList.toggle('selected',selected);button.setAttribute('aria-pressed',String(selected));});updateOilCoatingChoice();});
