const {createHmac,timingSafeEqual}=require('node:crypto');
const SITE='https://floorman-estimator.vercel.app';
function signature(payload){if(!process.env.RESEND_API_KEY)throw new Error('Email service is not configured');return createHmac('sha256',process.env.FOLLOWUP_SIGNING_SECRET||process.env.RESEND_API_KEY).update('floorman-followup-cancel-v1:'+payload).digest('base64url');}
function stopToken(id,time=Date.now()){const payload=Buffer.from(JSON.stringify({id,expires:time+14*86400000})).toString('base64url');return payload+'.'+signature(payload);}
function parseToken(token){if(typeof token!=='string'||token.length>1000)throw new Error('Invalid stop link');const [payload,mac,...extra]=token.split('.');if(extra.length||!payload||!mac)throw new Error('Invalid stop link');const expected=Buffer.from(signature(payload)),actual=Buffer.from(mac);if(actual.length!==expected.length||!timingSafeEqual(actual,expected))throw new Error('Invalid stop link');const data=JSON.parse(Buffer.from(payload,'base64url').toString());if(!/^[a-zA-Z0-9-]{1,100}$/.test(data.id)||!Number.isFinite(data.expires)||data.expires<Date.now())throw new Error('This stop link has expired');return data.id;}
async function emailRequest(path,payload,key){for(let attempt=0;attempt<3;attempt++){const response=await fetch('https://api.resend.com'+path,{method:'POST',headers:{Authorization:'Bearer '+process.env.RESEND_API_KEY,'Content-Type':'application/json',...(key?{'Idempotency-Key':key}:{})},...(payload?{body:JSON.stringify(payload)}:{}),signal:AbortSignal.timeout(10000)});const data=await response.json();if(response.status===429&&attempt<2){await new Promise(resolve=>setTimeout(resolve,1000*(attempt+1)));continue;}return{ok:response.ok,status:response.status,data};}throw new Error('Email request failed');}
function followupEmail(customer,type,submittedAt=Date.now()){const service=type==='Concrete'?'concrete':'timber';const text=['Hi '+customer.name+',','','Just checking in about your '+service+' flooring enquiry with Floorman Waikato.','Would you like to discuss the work, ask any questions or arrange a site visit?','Reply to this email or call Jamie on 021 986 127.','','If you have already spoken with Jamie, you can disregard this reminder.','','Thanks,','Jamie','Floorman Waikato'].join('\n');return{from:'Floorman Estimator <estimator@floorman.co.nz>',to:[customer.email.trim()],reply_to:'jamie@floorman.co.nz',subject:'Any questions about your flooring enquiry?',text,scheduled_at:new Date(submittedAt+5*86400000).toISOString()};}
async function scheduleFollowup(customer,type,submission){const result=await emailRequest('/emails',followupEmail(customer,type,submission?.time),submission?.id?'followup-'+submission.id:undefined);if(!result.ok||!result.data.id)throw new Error('Follow-up could not be scheduled');return{id:result.data.id,stopUrl:SITE+'/api/stop-followup?token='+encodeURIComponent(stopToken(result.data.id,submission?.time))};}
async function cancelFollowup(id){return emailRequest('/emails/'+encodeURIComponent(id)+'/cancel');}
module.exports={scheduleFollowup,cancelFollowup,parseToken,stopToken,followupEmail,emailRequest};
